### ISSUE TITLE
[1.20.1] Chunk generation crash upon entering rift

### ISSUE THREAD

**Issue by Not-February** [DavidQF555/Multiverse#14]
I'm still experiencing #12 with Multiverse 3.0.3.

It doesn't always happen, but more often than not I can replicate it by just making new worlds and generating new rifts with the kaleidite cores. Sooner or later, the deadlock will happen.

I, too, am running a rather large modpack with a lot of customizations - which unfortunately makes it a lot harder to isolate whether it's a mod conflict or not. Please let me know if you need more information.

Here's some logs and a relevant thread dump.

[latest.log](https://github.com/user-attachments/files/18156226/latest.log)
[debug.log](https://github.com/user-attachments/files/18156223/debug.log)

[threaddump.txt](https://github.com/user-attachments/files/18156213/threaddump.txt)

**Comment by Not-February** [comment]
I compared my mod list with the mod list originally posted in #12 and did some testing with the mods we had in common.

I wasn't able to reproduce it with only Multiverse installed, so after testing I'm pretty sure it's an interaction with Alex's Caves; I can reproduce the deadlock with only `Multiverse 3.0.3` and `Citadel 2.6.0`/`Alex's Caves 2.0.2` installed. 

[latest.log](https://github.com/user-attachments/files/18196306/latest.log)
[debug.log](https://github.com/user-attachments/files/18196307/debug.log)
[crash-2024-12-19_02.23.48-server.txt](https://github.com/user-attachments/files/18196309/crash-2024-12-19_02.23.48-server.txt)


What's interesting about this is that when I originally encountered the issue, I was using a custom datapack that restricted which biomes Multiverse was allowed to generate with - and Alex's Caves biomes were _not_ on that list(specifically because I suspected their special generation would cause problems). It seems it happens regardless of whether Multiverses are actually configured to allow Alex's Caves biomes to spawn - in the logs I'm providing here, I'm using only the default settings of both mods.

**Comment by DavidQF555** [comment]
As far as I can tell, I don't think it's an issue of deadlocking. It seems to be crashing relating to a tag missing. I'm working on a structural update right now, and I think it may fix this.

**Comment by Apollonu** [comment]
I am also having a crash when someone enters a rift on forge 1.20.1, with World Host my friend entered a multiverse and it instantly crashed the game, I was met with the server closed message. It is blaming WF's Cave Overhaul for it but I am skeptical
```
Caused by: java.lang.IllegalArgumentException: bound - origin is non positive
	at net.minecraft.util.RandomSource.m_216339_(RandomSource.java:86) ~[client-1.20.1-20230612.114412-srg.jar%23940!/:?]
	at wftech.caveoverhaul.carvertypes.VanillaCanyon.m_213788_(VanillaCanyon.java:67) ~[caveoverhaul-forge-1.20.1-1.3.4.jar%23600!/:forge-1.20.1-1.3.4]
	at wftech.caveoverhaul.carvertypes.VanillaCanyon.m_213788_(VanillaCanyon.java:21) ~[caveoverhaul-forge-1.20.1-1.3.4.jar%23600!/:forge-1.20.1-1.3.4]
	at net.minecraft.world.level.levelgen.carver.ConfiguredWorldCarver.m_224898_(ConfiguredWorldCarver.java:35) ~[client-1.20.1-20230612.114412-srg.jar%23940!/:?]
	at net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator.m_213679_(NoiseBasedChunkGenerator.java:282) ~[client-1.20.1-20230612.114412-srg.jar%23940!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_289182_(ChunkStatus.java:101) ~[client-1.20.1-20230612.114412-srg.jar%23940!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus$SimpleGenerationTask.m_214024_(ChunkStatus.java:309) ~[client-1.20.1-20230612.114412-srg.jar%23940!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_280308_(ChunkStatus.java:252) ~[client-1.20.1-20230612.114412-srg.jar%23940!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMap.java:643) ~[client-1.20.1-20230612.114412-srg.jar%23940!/:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-6.0.8.jar%2395!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$29(ChunkMap.java:634) ~[client-1.20.1-20230612.114412-srg.jar%23940!/:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.20.1-20230612.114412-srg.jar%23940!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.20.1-20230612.114412-srg.jar%23940!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.20.1-20230612.114412-srg.jar%23940!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.20.1-20230612.114412-srg.jar%23940!/:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
```
[latest.log](https://github.com/user-attachments/files/22959773/latest.log)

**Comment by DavidQF555** [comment]
This is an incompatibility from WF's Cave Overhaul. Basically, the VanillaCanyon feature is expecting to be in a world of a certain size (min/max Y values). When it is in a multiverse dimension, its logic may go out of bounds, causing a crash.

**Comment by Not-February** [comment]
Just curious - is there no way to prevent WF's Cave Overhaul from affecting Multiverses specifically or does it overwrite the vanilla cave generation in such a way that this isn't possible?

**Comment by DavidQF555** [comment]
Features and carvers are per biome so you would need to remove the affected biomes from Multiverse dimensions. The biomes that appear in Multiverse dimensions can be configured with a data pack, though it uses a white-list so black-listing is a bit of a pain.
